### ISSUE TITLE
ValueError: could not broadcast input array from shape (224,224,3) into shape (224,224

### ISSUE THREAD

**Issue by wang7393** [ck196/tensorflow-alexnet#2]
I run my own dataset, it apper the following error,why?

Run id: alexnet_oxflowers17
Log directory: output/
Traceback (most recent call last):
  File "tflearn_alexnet_end2end.py", line 124, in <module>
    train(net,X,Y) 
  File "tflearn_alexnet_end2end.py", line 111, in train
    model.fit(X, Y, n_epoch=1000, validation_set=0.1, shuffle=True, show_metric=True, batch_size=64, snapshot_step=200, snapshot_epoch=False, run_id='alexnet_oxflowers17') 
  File "build/bdist.linux-x86_64/egg/tflearn/models/dnn.py", line 216, in fit
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py", line 269, in fit
  File "build/bdist.linux-x86_64/egg/tflearn/utils.py", line 160, in standarize_dict
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (224,224,3) into shape (224,224)

**Comment by ck196** [comment]
Can you check you input images?
Image shape must be [224, 224, 3] (RGB) but your input image shape is [224, 224] in grayscale.
